acqu-hire/AcquhireTeamPrj

src/main/resources/mapper/noticeMapper.xml

noticeMapper 생성

---

src/main/resources/mapper/communityMapper.xml
src/test/java/com/aqh/board/domain/dao/CommunityDAOTest.java

+ communityMapper Fix
+ CommunityDAO Junit Test Case

✅ Add, Test Case

---

src/main/java/com/aqh/board/controller/QnAController.java
src/main/webapp/WEB-INF/views/include/header.jsp
src/test/java/com/aqh/board/domain/dao/QnADAOTest.java

:wrench:Controller,header,Test 수정

---

src/main/java/com/aqh/board/domain/dao/NoticeDAO.java
src/main/resources/mapper/noticeMapper.xml

Kdy develop - noticeDAO, noticeMapper 생성

---

src/main/java/com/aqh/board/controller/QnAController.java
src/main/resources/mapper/qnaMapper.xml
src/main/webapp/WEB-INF/views/board/qna/qna_list_detail.jsp
src/main/webapp/WEB-INF/views/board/qna/qna_update_form.jsp

✨QnAController 추가
✨View페이지 jsp 추가
:wrench:qnaMapper 수정

23.01.04 기능 추가 및 수정

---

src/main/java/com/aqh/board/controller/QnAController.java
src/main/java/com/aqh/board/domain/dao/QnADAO.java
src/main/java/com/aqh/board/service/QnAService.java
src/main/resources/mapper/qnaMapper.xml
src/main/webapp/WEB-INF/views/board/qna/qna_list.jsp
src/main/webapp/WEB-INF/views/board/qna/qna_write.jsp

:sparkles: 글쓰기폼 카테고리 추가

---

src/main/java/com/aqh/board/controller/QnAController.java
src/main/java/com/aqh/board/domain/dao/QnADAO.java
src/main/java/com/aqh/board/domain/pagehandler/PageHandler.java
src/main/java/com/aqh/board/service/QnAService.java
src/main/resources/mapper/qnaMapper.xml
src/main/webapp/WEB-INF/views/board/qna/qna_list.jsp
src/main/webapp/WEB-INF/views/include/header.jsp
src/test/java/com/aqh/test/UriComponentsTest.java

:sparkles:QnA게시판 페이징처리 및 PageHandler.java 추가
:wrench: header.jsp 수정

페이징 구현 및 레이아웃 수정

---

src/main/java/com/aqh/board/domain/dao/QnADAO.java
src/main/java/com/aqh/board/domain/pagehandler/PageHandler.java
src/main/java/com/aqh/board/service/QnAService.java
src/main/webapp/WEB-INF/views/board/qna/qna_list.jsp
src/main/webapp/WEB-INF/views/include/footer.jsp
src/main/webapp/WEB-INF/views/include/header.jsp
src/main/webapp/WEB-INF/views/index.jsp
src/test/java/com/aqh/board/domain/dao/QnADAOTest.java

:sparkles:카테고리탭 동적 활성화

---

src/main/java/com/aqh/board/domain/dao/QnADAO.java
src/main/java/com/aqh/board/service/QnAService.java

:white_check_mark: QnADAO,QnAService 수정

:white_check_mark: QnADAO,QnAService 수정

---

src/main/java/com/aqh/board/domain/pagehandler/PageHandler.java
src/main/webapp/WEB-INF/views/board/qna/qna_list.jsp
src/main/webapp/WEB-INF/views/board/qna/qna_update_form.jsp
src/main/webapp/WEB-INF/views/board/qna/qna_write.jsp

:wrench:페이징 오류 jsp페이지 수정

---

src/main/java/com/aqh/board/controller/QnAController.java
src/main/java/com/aqh/board/domain/dao/QnADAO.java
src/main/java/com/aqh/board/domain/pagehandler/PageHandler.java
src/main/java/com/aqh/board/domain/pagehandler/SearchCondition.java
src/main/java/com/aqh/board/service/QnAService.java
src/main/resources/mapper/qnaMapper.xml
src/main/webapp/WEB-INF/views/board/qna/qna_list.jsp

✨게시판 검색기능 추가

---

src/main/resources/mapper/eventMapper.xml

event mapper 설정

---

src/main/java/com/aqh/board/controller/QnAController.java
src/main/java/com/aqh/board/domain/pagehandler/PageHandler.java
src/main/resources/mapper/qnaMapper.xml
src/main/webapp/WEB-INF/views/board/qna/qna_list.jsp
src/main/webapp/WEB-INF/views/board/qna/qna_list_detail.jsp

검색 후 카테고리 별 검색 분류와 탭 활성화 유지 수정

:wrench: 검색페이지 카테고리 유지 수정

---

src/main/java/com/aqh/board/controller/QnAController.java
src/main/java/com/aqh/member/domain/dto/MemberDTO.java
src/main/webapp/WEB-INF/views/board/qna/qna_list_detail.jsp
src/main/webapp/WEB-INF/views/board/qna/qna_update_form.jsp
src/main/webapp/WEB-INF/views/board/qna/qna_write.jsp

QnA CRUD 1차 마무리

---

src/main/java/com/aqh/board/domain/pagehandler/PageHandler.java
src/main/java/com/aqh/member/controller/MemberController.java
src/main/java/com/aqh/member/domain/dao/MemberDAO.java
src/main/java/com/aqh/member/service/MemberService.java
src/main/resources/mapper/memberMapper.xml
src/main/webapp/WEB-INF/views/include/header.jsp
src/main/webapp/WEB-INF/views/member/register_form.jsp
src/main/webapp/resources/js/kakao-addressAPI.js

controller, dao, service, mapper, jsp 추가

:sparkles: 회원가입 관련 클래스 및 매퍼 생성

---

src/main/java/com/aqh/login/controller/LoginController.java
src/main/java/com/aqh/member/controller/MemberController.java
src/main/java/com/aqh/member/domain/dao/MemberDAO.java
src/main/java/com/aqh/member/domain/dto/MemberDTO.java
src/main/java/com/aqh/member/service/MemberService.java
src/main/resources/mapper/memberMapper.xml
src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
src/main/webapp/WEB-INF/views/board/qna/qna_list.jsp
src/main/webapp/WEB-INF/views/board/qna/qna_list_detail.jsp
src/main/webapp/WEB-INF/views/board/qna/qna_update_form.jsp
src/main/webapp/WEB-INF/views/board/qna/qna_write.jsp
src/main/webapp/WEB-INF/views/include/header.jsp
src/main/webapp/WEB-INF/views/login/login_form.jsp
src/main/webapp/WEB-INF/views/member/member_info.jsp
src/main/webapp/WEB-INF/views/member/register_form.jsp

:sparkles:로그인, 회원가입 1차 완성

---

src/main/java/com/aqh/board/controller/QnAController.java
src/main/java/com/aqh/login/controller/LoginController.java
src/main/java/com/aqh/member/controller/MemberController.java
src/main/java/com/aqh/member/domain/dao/MemberDAO.java
src/main/java/com/aqh/member/domain/dto/MemberDTO.java
src/main/java/com/aqh/member/service/MemberService.java
src/main/resources/mapper/memberMapper.xml
src/main/webapp/WEB-INF/views/board/qna/qna_list.jsp
src/main/webapp/WEB-INF/views/board/qna/qna_list_detail.jsp
src/main/webapp/WEB-INF/views/board/qna/qna_update_form.jsp
src/main/webapp/WEB-INF/views/board/qna/qna_write_form.jsp
src/main/webapp/WEB-INF/views/include/header.jsp
src/main/webapp/WEB-INF/views/login/login_form.jsp
src/main/webapp/WEB-INF/views/member/member_info.jsp
src/main/webapp/WEB-INF/views/member/member_update_form.jsp
src/main/webapp/WEB-INF/views/member/register_form.jsp

✨로그인 및 회원가입 추가
✨ 회원 개별조회,수정,삭제 추가

✨로그인 및 회원가입 추가, 회원 개별조회,수정,삭제 추가

---

src/main/webapp/WEB-INF/views/board/qna/qna_list_detail.jsp
src/main/webapp/WEB-INF/views/member/register_form.jsp
src/main/webapp/resources/js/validity.js

⚡글 수정,삭제 세션확인 추가

---

src/main/webapp/WEB-INF/views/include/header.jsp

header.jsp 충돌해결

---

src/main/java/com/aqh/board/controller/QnAController.java
src/main/webapp/WEB-INF/views/board/qna/qna_list.jsp
src/main/webapp/WEB-INF/views/board/qna/qna_update_form.jsp
src/main/webapp/WEB-INF/views/board/qna/qna_write_form.jsp

:wrech:jQuery 및 컨트롤러 수정

---

src/main/java/com/aqh/board/controller/QnAController.java
src/main/webapp/WEB-INF/views/board/qna/qna_list.jsp
src/main/webapp/WEB-INF/views/board/qna/qna_update_form.jsp
src/main/webapp/WEB-INF/views/board/qna/qna_write_form.jsp

🔧 jQuery 및 컨트롤러 수정
